apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: daystride

spec:
  type: ClusterIP
  selector:
    app: backend

  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: daystride

spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  revisionHistoryLimit: 8
  minReadySeconds: 10
  progressDeadlineSeconds: 300

  template:
    metadata:
      namespace: daystride
      labels:
        app: backend

    spec:
      initContainers:
        - name: wait-for-db-auth
          image: mysql:8.4
          command:
            - /bin/sh
            - -c
            - |
              echo "Checking DB readiness and user credentials at $DB_HOST:$DB_PORT..."
              while true; do
                if mysqladmin ping -h $DB_HOST -P $DB_PORT -u $DB_USER -p$DB_PASSWORD --silent; then
                  echo "Login with user '$DB_USER' successful. Proceeding to start backend."
                  exit 0
                else
                  echo "DB not ready or credentials invalid. Retrying in 5 seconds..."
                  sleep 5
                fi
              done
          envFrom:
            - secretRef:
                name: daystride-env-secret
      containers:
        - name: backend-container
          image: edon505/daystride-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: daystride-env-secret